### ISSUE TITLE
ModuleNotFoundError: No module named 'captcha'

### ISSUE THREAD

**Issue by josephtrinh** [michael-yin/wagtail-bootstrap-blog#147]
Not having too much luck with resolving this error with the captcha. 

`db-1   | 2024-01-26 02:42:39.259 UTC [21] LOG:  database system was shut down at 2024-01-25 18:51:39 UTC
db-1   | 2024-01-26 02:42:39.262 UTC [1] LOG:  database system is ready to accept connections
web-1  | PostgreSQL is available
web-1  | Traceback (most recent call last):
web-1  |   File "/app/manage.py", line 22, in <module>
web-1  |     main()
web-1  |   File "/app/manage.py", line 18, in main
web-1  |     execute_from_command_line(sys.argv)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
web-1  |     utility.execute()
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
web-1  |     django.setup()
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
web-1  |     apps.populate(settings.INSTALLED_APPS)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
web-1  |     app_config = AppConfig.create(entry)
web-1  |   File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
web-1  |     import_module(entry)
web-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
web-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
web-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
web-1  |   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
web-1  | ModuleNotFoundError: No module named 'captcha'
web-1 exited with code 1`

**Comment by michael-yin** [comment]
@josephtrinh 

Has been fixed in https://github.com/AccordBox/wagtail-tailwind-blog/commit/e7ea2b56c09c8a8f125461aa110468e2c565a277

Please try the latest version.

Thx.
