### ISSUE TITLE
error version django 2.0

### ISSUE THREAD

**Issue by lidymonteirowm** [michael-yin/wagtail-bootstrap-blog#5]
error running project in Django version 2.0

```
(.myvenv) FJN:wagtail-bootstrap-blog lidiane$ ./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x103cf4268>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lidiane/Developer/wagtail-bootstrap-blog/logs/django.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/lidiane/Developer/wagtail-bootstrap-blog/.myvenv/lib/python3.5/site-packages/django/utils/log.py", line 73, in configure_logging
    logging_config_func(logging_settings)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file_handler': [Errno 2] No such file or directory: '/Users/lidiane/Developer/wagtail-bootstrap-blog/logs/django.log'
```

**Comment by michael-yin** [comment]
@lidymonteirowm 

Hi, Try to create logs directory in your project directory using `mkdir logs`, thanks

**Comment by iris9112** [comment]
Other error for version 2.0 is  `does not define a "SessionAuthenticationMiddleware"`, you just need delete this line from yours base.py file.

**Comment by inyoka** [comment]
So other than this, does wagtail-bootstrap-blog work with Django 2.0?

**Comment by michael-yin** [comment]
@inyoka 

This project now work with Django 2.0. Sorry for the delay!
